config/routes.rb
Rails.application.routes.draw do
  
  # get request for omniauth / find or create user and initiate session
  get '/auth/:provider/callback', to: 'sessions#create'

  # redirect '/' to a home/welcome page
  root 'application#home'
  
  # signup / create a user
  get '/signup', to: 'users#new'
  
  # login & logout / create & destroy a session
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  # users / user/index / user/new
  resources :users, except: [:index, :new]
  
  # recipes / recipe/new / recipe/show nested into the current user
  resources :users, only: [] do 
    resources :recipes, only: [:new, :show]
  end 

  # recipes / only for index, create and show
  resources :recipes, only: [:index, :create]

  resources :recipes, only: [:show] do
    resources :ingredients, only: [:show]
    resources :recipe_ingredients, only: :new
  end

  resources :recipe_ingredients, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  validates :quantity, presence: true

  belongs_to :recipe 
  belongs_to :ingredient 
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :title, presence: true
  
  belongs_to :user
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  accepts_nested_attributes_for :recipe_ingredients, :ingredients

  scope :recent, -> { order("created_at DESC").limit(3) }

  def add_ingredients_to_recipe(params)
    params[:recipe_ingredients_attributes].each do |k, v|
      if v[:ingredient_attributes][:name].present?
        ingredient_name = v[:ingredient_attributes][:name].capitalize
        new_ingredient = Ingredient.find_or_create_by(name: ingredient_name)
      elsif v[:ingredient_id].present?
        new_ingredient = Ingredient.find_by(id: v[:ingredient_id])
      end
      if v[:quantity].present?
        RecipeIngredient.create(quantity: v[:quantity], ingredient_id: new_ingredient.id, recipe_id: self.id )
      end
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  validates :quantity, presence: true

  belongs_to :recipe
  belongs_to :ingredient

  accepts_nested_attributes_for :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :recipes
  has_many :ingredients, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user, :redirect_if_not_logged_in
  
  def home
    @recipes = Recipe.all
  end 

  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end 

  def redirect_if_not_logged_in
    if !logged_in?
      flash[:message] = "You are not logged in. Please Sign Up or Log In to continue."
      redirect_to root_path
    end
  end

  def redirect_if_logged_in
    if logged_in?
      flash[:message] = "You are already logged in."
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def show
    @ingredient = Ingredient.find_by(id: params[:id])
  end 
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  
  def new
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_ingredient = RecipeIngredient.new(recipe_id: params[:recipe_id])
  end

  def create
    set_ingredient
    @recipe_ingredient = RecipeIngredient.new(recipe_ingredients_params)
    @recipe_ingredient.ingredient_id = @ingredient.id
    if @recipe_ingredient.save
      redirect_to recipe_path(@recipe_ingredient.recipe_id)
    else
      render :new 
    end
  end

  def set_ingredient
    @ingredient = Ingredient.find_or_create_by(name: params[:recipe_ingredient][:ingredient_attributes][:name])
  end 
  
  private

  def ingredients_params
    params.require(:recipe_ingredient).permit(ingredient_attributes: [:name])
  end
  def recipe_ingredients_params
    params.require(:recipe_ingredient).permit(:ingredient_id, :recipe_id, :quantity)
  end
end 

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :redirect_if_not_logged_in
  
  def index
    @recipes = Recipe.all
  end 

  def new
    @recipe = Recipe.new
  end 

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      @recipe.add_ingredients_to_recipe(recipe_ingredients_params)
      redirect_to user_recipe_path(current_user, @recipe)
    else
      render :new 
    end
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end

  def recipe_ingredients_params
    params.require(:recipe).permit(recipe_ingredients_attributes: [:quantity, :ingredient_id, ingredient_attributes: [:name]])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:new]
  
  def new
  end

  def create
    if auth
      oauth_uid = auth["uid"]
      oauth_username = auth["info"]["nickname"]
      oauth_password = SecureRandom.hex
      if @user = User.find_by(uid: oauth_uid)
        log_in(@user)
      else
        @user = User.new(uid: oauth_uid, username: oauth_username, password: oauth_password)
        if @user.save
          log_in(@user)
        else 
          redirect_if_error_login
        end
      end 
    else
      @user = User.find_by(username: params[:username])
      if @user && @user.authenticate(params[:password])
        log_in(@user)
      else
        redirect_if_error_login
      end
    end 
  end

  def destroy
    session.clear
    flash[:message] = "You have successfully logged out"
    redirect_to root_path
  end

  private
  
  def auth 
    request.env['omniauth.auth']
  end

  def log_in(user)
    session[:user_id] = user.id
    flash[:message] = "You have successfully logged in"
    redirect_to user_path(@user)
  end

  def redirect_if_error_login
    flash[:message] = "Something went wrong"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_logged_in, only: [:show]
  before_action :redirect_if_logged_in, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:message] = "You have successfully logged in"
      redirect_to user_path(@user)
    else
      render :new
    end 
  end

  def show
    @user = User.find_by(id: params[:id])
  end 

  private
  
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_form_for_errors.erb
<% if obj_to_check.errors.any? %>
	<div id="error_explanation">
		<h3>There were some errors:</h3>
		<ul>
			<% obj_to_check.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/application/home.html.erb
<h2>Welcome to Gastronomicon</h2>
<% if !@recipes.empty? %>
  <% @recipes.recent.each do |r| %>
    <% if logged_in? %>
      <h3><%= link_to r.title, user_recipe_path(r.user, r) %></h3>
      <p>by: <%= link_to r.user.username, user_path(r.user) %></p>
    <% else %>
      <h3><%= r.title %></h3>
      <p>by: <%= r.user.username %></p>
    <% end %>
  <% end %>
<% else %>
  <p>There are currently no recipes to display</p>
<% end %>
<br>
<% if !logged_in?%>
  <p>Please <%= link_to "Sign Up", signup_path %> of <%= link_to "Log In", login_path %> so see more recipes.</p>
<% end %>

app/views/ingredients/show.html.erb
<h2>Recipes including <%= @ingredient.name %></h2>

<% @ingredient.recipes.each do |recipe| %>
  <div>
    <%= link_to recipe.title, recipe_path(recipe) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gastronomicon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header style="padding-bottom:30px;">
    <% if logged_in? %>
      <%= link_to "Home", root_path %>
      <%= link_to "View Recipes", recipes_path %>
      <%= link_to "My Recipes", user_path(current_user) %> 
      <%= link_to "Create New Recipe", new_user_recipe_path(current_user) %>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", login_path %>
      <%= link_to "Log In with Github", '/auth/github' %>
    <% end %>
  </header>
    <div style="color:red;">
      <%= flash[:message] if flash[:message] %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/recipe_ingredients/new.html.erb
<h2>Add a new ingredient for <%= @recipe.title %></h2>

<%= form_for @recipe_ingredient do |f| %>
  <%= render partial: 'application/form_for_errors', locals: {obj_to_check: @recipe_ingredient } %>
  <%= f.hidden_field :recipe_id %>
  <div>
    <%= f.fields_for :ingredient, @recipe.ingredients.build do |ingredient_fields| %>
      <%= ingredient_fields.label "Ingredient" %>
      <%= ingredient_fields.text_field :name %>
    <% end %>
    <%= f.label "Quantity:" %>
    <%= f.text_field :quantity %>
  </div>
  <br>
  <%= f.submit "Add Ingredient"%>
<% end %>

app/views/recipes/index.html.erb
<h2>All Gastronomicon's Recipes:</h2>
<% if !@recipes.empty? %>
  <% @recipes.each do |recipe| %>
    <h3><%= link_to recipe.title, user_recipe_path(recipe.user, recipe)  %></h3>
    <p>by: <%= link_to recipe.user.username, user_path(recipe.user) %></p>
    <p><%= recipe.description %></p>
  <% end %>
<% else %>
  <p>There are currently no recipes to display</p>
<% end %>

app/views/recipes/new.html.erb
<h2>Create a new recipe</h2>
<%= form_for @recipe do |f| %>
  <%= render partial: 'application/form_for_errors', locals: {obj_to_check: @recipe } %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
  </div>
  <br>
  <div>
    <p>Add your recipe's ingredients:</p>
    <%= f.fields_for :recipe_ingredients, 5.times { @recipe.recipe_ingredients.build } do |recipe_ingredients_fields| %>
      <div>
        <%= recipe_ingredients_fields.fields_for :ingredient, @recipe.ingredients.build do |ingredient_fields| %>
          <%= ingredient_fields.label "Ingredient" %>
          <%= ingredient_fields.text_field :name %>
        <% end %>
        <%= recipe_ingredients_fields.label "Quantity" %>
        <%= recipe_ingredients_fields.text_field :quantity %>
      <div>      
    <% end %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h2><%= @recipe.title%></h2>
<p>by: <%= link_to @recipe.user.username, user_path(@recipe.user) %></p>
<p><%= @recipe.description %></p>
<br>
<p>Ingredients:</p>
<ul>
  <% @recipe.ingredients.each do |ing| %>
    <li><%= link_to ing.name, recipe_ingredient_path(@recipe, ing) %>: 
    <% ing.recipe_ingredients.each do |i| %>
      <%= i.quantity %>
      <% end %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Add another ingredient", new_recipe_recipe_ingredient_path(@recipe) %></p>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<h3>Please enter your details below to Sign Up</h3>
<%= form_for @user do |f| %>
  <%= render partial: 'application/form_for_errors', locals: {obj_to_check: @user } %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username.capitalize %>'s Recipes</h2>
<% if @user.recipes == [] && @user == current_user %>
  <p>You have not created any recipes yet! Go ahead and <%= link_to "Create your first recipe", new_user_recipe_path(@user) %></p>
<% elsif @user.recipes == [] && @user != current_user %>
  <p><%= @user.username.capitalize %> has not created any recipes yet!</p>
<% else %>
  <% @user.recipes.each do |recipe| %>
    <h3><%= link_to recipe.title, user_recipe_path(@user, recipe) %></h3>
    <p><%= recipe.description %></p>
  <% end %>
<% end %>